<div class="module-group">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('featureproductslider.phtml')->toHtml();?>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Recentproductslider\Block\Products')->setTemplate('productslider.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>