<?php
/**
 * Copyright © 2016 PlazaThemes.com. All rights reserved.
 *
 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>

<?php
/**
 * Sale Products with Countdown
 *
 * @var $block \Plazathemes\Pricecountdown\Block\Pricecountdown
 * @var $_product \Magento\Catalog\Model\Product
 */
?>
<?php $slider_options = $block->getSliderOptions(); ?>
<?php
    $enable             = $slider_options['enabled'];
    $use_countdown      = $slider_options['use_countdown'];
    $title              = $slider_options['title'];
    $show_price         = $slider_options['show_price'];
    $show_add_cart      = $slider_options['show_add_cart'];
    $show_add_wishlist  = $slider_options['show_add_wishlist'];
    $show_add_compare   = $slider_options['show_add_compare'];
    $show_rating        = $slider_options['show_rating'];
    $show_short_des     = $slider_options['show_short_description'];
    $auto               = $slider_options['auto'];
    $speed              = $slider_options['speed'];
    $item_default       = $slider_options['item_default'];
    $item_desktop       = $slider_options['item_desktop'];
    $item_desktop_small = $slider_options['item_desktop_small'];
    $item_tablet        = $slider_options['item_tablet'];
    $item_mobile        = $slider_options['item_mobile'];
    $row_number         = $slider_options['row_number'];
    $show_navigation    = $slider_options['show_navigation'];
    $show_pagination    = $slider_options['show_pagination'];
	
	$image = 'category_page_grid';
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<?php if($enable): ?>
    <?php
        $_productCollection = $block->getSaleProducts();
        $imageDefine = 'new_products_content_widget_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    ?>
<div class="timerproducts module-product">	
	<div class="container">
	<div class="title">
	<h2><?php echo $title; ?></h2>
	<p><?php echo __('Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.') ?></p>
	</div>
	<div class="pricecountdown">
		<div class="countdown-thumb">
			<ul class="thumb">
				<?php
				 $j=0;
				foreach($_productCollection as $_product): ?>
				<?php $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(102)->getUrl(); ?>
				<li class="thumb<?php echo $j;  if($j == 0) echo ' active first';?>"><img src="<?php echo $productImage; ?>" alt=""/></li>
				<?php $j++; endforeach;  ?>
			</ul>
		</div>
		<div class="countdown-slider">
			<div id="sale-products-slider">
				
				<div class="owl-container">
					<div class="owl-carousel">
					<?php $count = 0; ?>
					<?php foreach($_productCollection as $_product): ?>
						<?php $productImage = $block->getImage($_product, $imageDefine); ?>
						<?php if($count++ % $row_number == 0 ) { echo '<div class="row_items">'; }  ?>
						<div class="item">
							<div class="item-inner">
								
								<div class="image-container">
									<?php
										$newFromDate = $_product->getNewsFromDate();
										$newToDate = $_product->getNewsToDate();                
										$now = date("Y-m-d H:m:s");
										// Get the Special Price
										$specialprice = $_product->getSpecialPrice(); 
										// Get the Special Price FROM date
										$specialPriceFromDate = $_product->getSpecialFromDate();
										// Get the Special Price TO date
										$specialPriceToDate = $_product->getSpecialToDate();
										// Get Current date
										if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
										$_savePercent = 100 - round(($_product->getSpecialPrice() / $_product->getPrice())*100);
										echo "<div class='hot-sale'><span>-".$_savePercent."%</span><small>Off</small></div>";
										}else{
										if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
										?>
										<div class="label-pro-new"><span><?php echo __('new') ?></span></div>
										<?php
										}
										}
									?>
									<a href="<?php echo $block->getProductUrl($_product) ?>" class="product-item-photo">
										<?php echo $productImage->toHtml() ?>
									</a>
									<div class="actions">
										<?php if ($show_add_cart): ?>
											<div class="actions-primary">
												<?php if ($_product->isSaleable()): ?>
													<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
														<button class="action tocart primary"
																data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_product) ?>"}}'
																type="button" title="<?php echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
														?>
														<button class="action tocart primary"
																data-post='<?php echo $postData; ?>'
																type="button" title="<?php echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php endif; ?>

										<?php if ($show_add_compare || $show_add_wishlist): ?>
											<div class="actions-secondary add-to-links" data-role="add-to-links">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $show_add_wishlist): ?>
													<a href="#"
													   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
													   class="action towishlist" data-action="add-to-wishlist"
													   title="<?php echo __('Add to Wishlist') ?>">
														<span><?php echo __('Add to Wishlist') ?></span>
													</a>
												<?php endif; ?>
												<?php if ($block->getAddToCompareUrl() && $show_add_compare): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
													<a href="#" class="action tocompare"
													   data-post='<?php echo $compareHelper->getPostDataParams($_product);?>'
													   title="<?php echo __('Add to Compare') ?>">
														<span><?php echo __('Add to Compare') ?></span>
													</a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
								</div>
								<div class="item-content des">
									<div class="product-name">
										<strong class="product-item-name">
											<a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
											   href="<?php echo $block->getProductUrl($_product) ?>"
											   class="product-item-link">
												<?php echo $block->escapeHtml($_product->getName()) ?>
											</a>
										</strong>
									</div>
									<?php if($show_rating): ?>
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?> 
										<?php endif; ?>
									<?php endif; ?>	
									<?php if($show_short_des): ?>
										<div class="short-description">
											<?php echo $block->getShortString($_product->getDescription()); ?>
										</div>
									<?php endif; ?>
									
									<?php if($show_price): ?>
										<?php echo $block->getProductPrice($_product); ?>
									<?php endif; ?>
									

									<!-- Price Countdown -->
									<?php if($use_countdown): ?>
										<?php if($_product->getShowCountdown() == 1): ?>
											<div class="countbox-<?php echo $_product->getId(); ?> countdown-container">
												<div class='datetime'>
													<span class='day'><?php echo __('D') ?></span>
													<span class='hour'><?php echo __('H') ?></span>
													<span class='min'><?php echo __('M') ?></span>
													<span class='sec'><?php echo __('S') ?></span>
												</div>
											</div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
							</div>
						</div>
						<?php if($count % $row_number == 0 || $count == count($_productCollection)) { echo '</div>'; }  ?>
					<?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
    <!-- Price Countdown -->
    <?php if($use_countdown): ?>
        <?php foreach ($_productCollection as $_product): ?>
            <?php if($_product->getShowCountdown() == 1): ?>
                <?php
                    $toDate = $_product->getSpecialToDate();
                    $fromDate = $_product->getSpecialFromDate();
                    $_current_timer = time();
                ?>
                <script type="text/javascript">
                    var dthen<?php echo $_product->getId(); ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
                    var start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
                    var start_date = Date.parse(start);
                    var dnow<?php echo $_product->getId(); ?> = new Date(start_date);

                    var ddiff;
                    if(CountStepper > 0) {
                        ddiff= new Date((dnow<?php echo $_product->getId(); ?>)-(dthen<?php echo $_product->getId(); ?>));
                    } else {
                        ddiff = new Date((dthen<?php echo $_product->getId(); ?>)-(dnow<?php echo $_product->getId(); ?>));
                    }

                    <?php if(strtotime($fromDate) <= $_current_timer): ?>
                        gsecs<?php echo $_product->getId(); ?> = Math.floor(ddiff.valueOf()/1000);
                    <?php else: ?>
                        gsecs<?php echo $_product->getId(); ?> = -1;
                    <?php endif; ?>

                    var iid<?php echo $_product->getId(); ?> = "countbox-<?php echo $_product->getId(); ?>";
                    CountBack_slider(gsecs<?php echo $_product->getId(); ?>,"countbox-<?php echo $_product->getId(); ?>", <?php echo $_product->getId(); ?>);
                </script>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <script type="text/javascript">
        require(["jquery","owlcarousel/minjs","slickmin"], function($,owlCarousel){
            $("#sale-products-slider .owl-carousel").owlCarousel({
                autoPlay :          <?php if($auto) echo 'true'; else echo 'false'; ?>,
                slideSpeed :        <?php echo $speed; ?>,
                items :             <?php echo $item_default; ?>,
                itemsDesktop :      [1199,<?php echo $item_desktop; ?>],
                itemsDesktopSmall : [992,<?php echo $item_desktop_small; ?>],
                itemsTablet:        [768,<?php echo $item_tablet; ?>],
                itemsMobile :       [480,<?php echo $item_mobile; ?>],
                navigation :        <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
                stopOnHover :       true,
                pagination :        <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
				afterMove: function(){
					x = $( "#sale-products-slider .owl-carousel .owl-pagination .owl-page" ).index( $( ".pricecountdown .owl-pagination .active" ));
					var thumb = ".thumb"+x;
					$(".pricecountdown .thumb li").removeClass('current');
					$(thumb).addClass('current');
				}
            });
			
			var owltimerslider = $("#sale-products-slider .owl-carousel").data('owlCarousel');
						
			function timerslider(x)
			{
				owltimerslider.goTo(x)
			}
			$('.pricecountdown .thumb li.first').addClass('current');
			$('.pricecountdown .thumb li').click(function(){
				var x = $('.pricecountdown .thumb li').index(this);
				timerslider(x);
				$('.pricecountdown .thumb li').removeClass('current');
				$(this).addClass('current');
			})
			
			$(".pricecountdown .thumb").slick({
				dots: false,
				slidesToShow: 4,
				slidesToScroll: 1,
				vertical: true,
				infinite: false,
				responsive: [
					{
					  breakpoint: 1199,
					  settings: {
						slidesToShow: 4,
					  }
					},
					{
					  breakpoint: 992,
					  settings: {
						slidesToShow: 4,
					  }
					},
					{
					  breakpoint: 768,
					  settings: {
						slidesToShow: 4,
					  }
					},
					{
					  breakpoint: 480,
					  settings: {
						slidesToShow: 4,
					  }
					}
					// You can unslick at a given breakpoint now by adding:
					// settings: "unslick"
					// instead of a settings object
				]
			})
        });
    </script>
<?php endif; ?>
